const studentdata=[
    {
        id:1,
        Name:"Alagupandi",
        Dep:"Mech",
        Sem:8,
        Cgpa:8.2
    },
    {
        id:2,
        Name:"Ajeeth",
        Dep:"Mech",
        Sem:8,
        Cgpa:8.1
    },
    {
        id:3,
        Name:"Arun",
        Dep:"Ece",
        Sem:8,
        Cgpa:8.6
    },
    {
        id:4,
        Name:"Sushmitha",
        Dep:"CSE",
        Sem:8,
        Cgpa:8.9,
    },
    {
        id:5,
        Name:"Sudharson",
        Dep:"Civil",
        Sem:8,
        Cgpa:8.5
    },
    {
        id:6,
        Name:"Sudhakar",
        Dep:"EEE",
        Sem:8,
        Cgpa:8.6
    },
   
  ]
export default studentdata;  